site_name: CiviCRM Documentation

theme:
  name: material
  custom_dir: overrides
  logo: img/civicrm-logo.svg
  features:
    - navigation.tabs

extra_css:
  - css/extra.css

plugins:
  - search
  - categories:
      generate_index: true
      verbose: false
      base_name: 'page-types'
      section_title: 'Page type:'
      no_nav: false
      category_separator: '|'
  - tags:
      tags_file: tags.md
      tags_template: overrides/tags.md.template
  - mkdocs-breadcrumbs-plugin:
      delimiter: " &gt; "  # separator between sections
      log_level: "WARNING"  # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        - "docs/mkdocs/**"
        - "docs/mkdocs"   # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
      use_page_titles: true # use page title instead of path in breadcrumbs
      home_text: "Home"

# Don't make any changes below this line. nav will be generated here.

