site_name: CiviCRM Documentation

theme:
  name: material
  features:
    - navigation.tabs

plugins:
  - search
  - tags
  - categories
  - mkdocs-breadcrumbs-plugin:
      delimiter: " &gt; "  # separator between sections
      log_level: "WARNING"  # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        - "docs/mkdocs/**"
        - "docs/mkdocs"   # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
      use_page_titles: true # use page title instead of path in breadcrumbs
      home_text: "Home"

# Don't make any changes below this line. nav will be generated here.

